---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db-service
    app: voting-app
spec:
  type: ClusterIP
  selector:
    app: voting-app
    name: postgres-pod
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432