---
apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    app: voting-app
spec:
  type: LoadBalancer
  selector:
    app: voting-app
    name: result-app-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80